name: debit_credit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.0.3289
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
